import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "@/app/components/site-shell";
import { Breadcrumbs, PageFinalCta } from "@/app/components/subpage";
import { articles } from "@/app/data";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map((article)=>({slug:article.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const article=articles.find((item)=>item.slug===slug);if(!article)return{};return{title:article.title,description:article.summary,alternates:{canonical:`https://www.fimmick.com/en/knowledge-hub/${article.slug}`},openGraph:{type:"article",title:article.title,description:article.summary,publishedTime:article.date,authors:[article.author],images:[]},twitter:{title:article.title,description:article.summary,images:[]}};}

export default async function ArticlePage({params}:Props){
  const{slug}=await params;const article=articles.find((item)=>item.slug===slug);if(!article)notFound();const related=articles.filter((item)=>item.slug!==slug).slice(0,3);
  const articleUrl=`https://www.fimmick.com/en/knowledge-hub/${article.slug}`;
  const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.summary,datePublished:article.date,dateModified:article.date,author:{"@type":"Organization",name:article.author},publisher:{"@type":"Organization",name:"FIMMICK",url:"https://www.fimmick.com"},mainEntityOfPage:`https://www.fimmick.com/en/knowledge-hub/${article.slug}`,articleSection:article.category};
  return <SiteShell><main id="main-content">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
    <div className="subpage-nav page-grid"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Knowledge Hub",href:"/en/knowledge-hub"},{label:article.category}]} /></div>
    <header className="article-hero"><div className="article-hero-signal" aria-hidden="true"><i/><i/><i/><span/></div><div className="page-grid"><div className="article-heading"><p className="kicker">{article.category}</p><h1>{article.title}</h1><p>{article.summary}</p></div><div className="article-header-meta"><div><span>Published</span><time dateTime={article.date}>{article.displayDate}</time></div><div><span>Reading time</span><strong>{article.readTime}</strong></div><div><span>Author</span><strong>{article.author}</strong></div></div></div></header>
    <section className="article-body section-light"><div className="article-layout page-grid"><aside><p className="kicker">On this page</p>{article.sections.map((section,index)=><a href={`#section-${index+1}`} key={section.heading}><span>0{index+1}</span>{section.heading}</a>)}<div className="share-block"><span>Share /</span><a href={`mailto:?subject=${encodeURIComponent(article.title)}&body=${encodeURIComponent(articleUrl)}`}>Email ↗</a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(articleUrl)}`} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></aside><article><p className="article-deck">The practical question is not whether a team can use AI. It is whether the organisation can connect AI to trusted context, real responsibility, measurable work, and human decision-making.</p>{article.sections.map((section,index)=><section id={`section-${index+1}`} key={section.heading}><span className="case-section-no">{String(index+1).padStart(2,"0")} / {article.category}</span><h2>{section.heading}</h2><p>{section.body}</p>{index===0&&<blockquote>Build the operating contract before scaling the agent.</blockquote>}</section>)}<div className="article-action"><p className="kicker">Apply the framework</p><h2>Map the first workflow with FIMMICK.</h2><p>Use the free industry benchmark to identify where intelligence, automation, and human approval can create the most immediate value.</p><Link className="button button-dark" href="/en/contact?intent=benchmark">Get Your Benchmark ↗</Link></div><div className="author-block"><span>F</span><div><p className="kicker">About the author</p><h3>FIMMICK</h3><p>AI business transformation agency deploying managed AI agents across marketing, sales, content, reporting, and customer engagement in eight Asian markets.</p></div></div></article></div></section>
    <section className="related-articles section-offwhite"><div className="section-head page-grid"><p className="section-index">Continue reading</p><div><p className="kicker">Related intelligence</p><h2>Build the connected view.</h2></div></div><div className="related-grid page-grid">{related.map((item)=><Link href={`/en/knowledge-hub/${item.slug}`} key={item.slug}><p className="kicker">{item.category}</p><h3>{item.title}</h3><p>{item.summary}</p><span>{item.readTime} ↗</span></Link>)}</div></section>
    <PageFinalCta title="Turn insight into an operating advantage." />
  </main></SiteShell>;
}
