import type { Metadata } from "next";
import Link from "next/link";
import { SiteShell } from "@/app/components/site-shell";
import { Breadcrumbs, MetricBand, PageFinalCta, SubpageHero } from "@/app/components/subpage";
import { aboutDeepDives } from "@/app/section-data";

export const metadata: Metadata={title:"About FIMMICK — Hong Kong AI Transformation Agency",description:"Founded in 2008 and based in Hong Kong, FIMMICK combines AI transformation, digital operating expertise, managed agents, data, automation, creativity, and local intelligence across Asia.",alternates:{canonical:"https://www.fimmick.com/en/about"}};

const timeline=[
  ["2008","Built deep experience in digital execution, campaigns, and local market behaviour."],
  ["2012","Developed cross-border operating experience and regional market understanding."],
  ["2016","Built repeatable industry playbooks across retail, finance, F&B, beauty, and more."],
  ["2019","Moved beyond campaigns into CRM, analytics, data, automation, and platform thinking."],
  ["2024","Started turning workflows into agents and agents into reusable templates."],
  ["2026","Evolved from project delivery toward an AI-enabled platform operating model."],
];

export default function AboutPage(){return <SiteShell><main id="main-content">
  <div className="subpage-nav page-grid"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"About"}]} /></div>
  <SubpageHero eyebrow="FIMMICK / Hong Kong → Asia" title={<>Built on digital experience.<br /><em>Rebuilt for AI.</em></>} intro="Since 2008, FIMMICK has helped more than 500 brands grow across Asia. Today, that experience powers managed AI workforces connected to real business operations." code="A/01"><div className="button-row"><Link className="button button-primary" href="/en/contact">Work with FIMMICK ↗</Link><a className="button button-secondary" href="#journey">Our journey ↓</a></div></SubpageHero>
  <MetricBand metrics={[{value:"2008",label:"founded in Hong Kong"},{value:"500+",label:"brands served"},{value:"8",label:"Asian markets"},{value:"4,000+",label:"AI agents deployed"}]} />
  <section className="about-belief section-offwhite"><div className="page-grid"><p className="section-index">Our belief</p><blockquote>AI becomes valuable only when it is connected to <em>real work.</em></blockquote><div><p>Start with a business problem.</p><p>Redesign the workflow.</p><p>Connect the right data.</p><p>Deploy managed AI teammates.</p><p>Keep people in control of judgment, approval, and final decisions.</p></div></div></section>
  <section className="hub-path-section section-light"><div className="section-head page-grid"><p className="section-index">01 / Explore FIMMICK</p><div><p className="kicker">Four perspectives</p><h2>Understand the company behind the AI workforce.</h2><p className="section-intro">Explore the story, method, Asian delivery model, and operating strengths that shape every platform and transformation engagement.</p></div></div><div className="hub-path-grid page-grid">{aboutDeepDives.map((page,index)=><Link href={`${page.parentHref}/${page.slug}`} key={page.slug}><span>{String(index+1).padStart(2,"0")} / {page.eyebrow}</span><h3>{page.seoTitle}</h3><p>{page.description}</p><strong>Explore this perspective ↗</strong></Link>)}</div></section>
  <section className="journey-section section-light" id="journey"><div className="section-head page-grid"><p className="section-index">02 / Our journey</p><div><p className="kicker">Experience that became infrastructure</p><h2>From campaigns to operating systems.</h2></div></div><div className="timeline page-grid">{timeline.map(([year,copy],index)=><article key={year}><span>{year}</span><i aria-hidden="true"/><p>{copy}</p><em>0{index+1}</em></article>)}</div></section>
  <section className="method-section section-ink"><div className="section-head page-grid"><p className="section-index">03 / Method</p><div><p className="kicker">Systems thinking in practice</p><h2>Six disciplines. One operating model.</h2></div></div><div className="discipline-grid page-grid">{[["Strategy","Define the business problem, value case, and decision rights."],["Intelligence","Observe market, customer, category, and performance signals."],["Data","Create trusted context across systems and operating definitions."],["Automation","Turn repeated work into reliable, observable execution."],["Creativity","Generate and iterate within a clear brand and human review system."],["Governance","Keep ownership, approval, risk, and learning visible."]].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="ecosystem-section section-light"><div className="section-head page-grid"><p className="section-index">04 / Ecosystem</p><div><p className="kicker">Specialised units, shared intelligence</p><h2>Built to understand real markets.</h2><p className="section-intro">The FIMMICK ecosystem includes focused platforms and business units that connect AI, advocacy, commerce, community, and cultural purpose.</p></div></div><div className="ecosystem-grid page-grid">{[["AIP","Managed AI Agent Platform and reusable workforce roles."],["KOCmax","KOC intelligence, advocacy, and community operations."],["Adfocate","Structured creator and customer advocacy programmes."],["Kinnso","Hong Kong discovery, offers, commerce, and audience intelligence."],["50 Add Oil","Content, advocacy, and experiences for Hong Kong’s 50+ audience."],["Eldage","Heritage storytelling, community, commerce, and cultural impact."]].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="asia-culture section-cobalt"><div className="page-grid"><p className="section-index">05 / Culture</p><div><h2>Hong Kong-rooted.<br/>Asia-scale.<br/><em>Globally ambitious.</em></h2><p>We value clear thinking, commercial usefulness, local nuance, controlled experimentation, and the discipline to turn a promising idea into reliable operations.</p></div></div></section>
  <PageFinalCta title="Build the next FIMMICK chapter with us." copy="Work with a transformation partner that understands the systems, channels, languages, and operating realities of Asia." />
</main></SiteShell>}
