import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "@/app/components/site-shell";
import { Breadcrumbs, PageFinalCta, SubpageHero } from "@/app/components/subpage";
import { industries } from "@/app/data";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return industries.map(({slug})=>({slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const industry=industries.find(x=>x.slug===slug);if(!industry)return{};return{title:industry.seoTitle,description:industry.description,keywords:industry.keywords,alternates:{canonical:`https://www.fimmick.com/en/industries/${slug}`},openGraph:{title:`${industry.seoTitle} | FIMMICK`,description:industry.description,images:[]},twitter:{title:`${industry.seoTitle} | FIMMICK`,description:industry.description,images:[]}};}

export default async function IndustryPage({params}:Props){const{slug}=await params;const industry=industries.find(x=>x.slug===slug);if(!industry)notFound();const schema={"@context":"https://schema.org","@type":"Service",name:industry.seoTitle,description:industry.description,provider:{"@type":"Organization",name:"FIMMICK",url:"https://www.fimmick.com"},areaServed:["Hong Kong","Taiwan","Japan","Singapore","Malaysia","Thailand","Philippines","China"],audience:{"@type":"BusinessAudience",audienceType:industry.name}};return <SiteShell><main id="main-content">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <div className="subpage-nav page-grid"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Industries",href:"/en/industries"},{label:industry.name}]} /></div>
  <SubpageHero eyebrow={`${industry.name} / AI transformation`} title={<>{industry.name.split(" & ")[0]}<br/><em>{industry.name.includes(" & ")?`& ${industry.name.split(" & ")[1]}`:"AI workforce"}</em></>} intro={industry.description} code="I/D"><div className="button-row"><Link className="button button-primary" href={`/en/contact?intent=${industry.slug}-benchmark`}>Get Your Industry Benchmark ↗</Link><a className="button button-secondary" href="#workflows">Explore workflows ↓</a></div></SubpageHero>
  <section className="industry-challenge section-offwhite"><div className="section-head page-grid"><p className="section-index">01 / Industry reality</p><div><p className="kicker">The operating constraint</p><h2>{industry.challenge}</h2></div></div></section>
  <section className="industry-workflows section-light" id="workflows"><div className="section-head page-grid"><p className="section-index">02 / Priority workflows</p><div><p className="kicker">Where the AI workforce works</p><h2>Four connected workflows. One measurable system.</h2></div></div><div className="industry-workflow-grid page-grid">{industry.workflows.map((flow,index)=><article key={flow.title}><span>{String(index+1).padStart(2,"0")}</span><h3>{flow.title}</h3><p>{flow.copy}</p></article>)}</div></section>
  <section className="industry-agents section-ink"><div className="section-head page-grid"><p className="section-index">03 / AI teammates</p><div><p className="kicker">A role-based workforce</p><h2>Configured around the industry—not a generic chatbot.</h2></div></div><div className="industry-agent-track page-grid">{industry.agents.map((agent,index)=><article key={agent}><span>0{index+1}</span><i aria-hidden="true"/><h3>{agent}<br/>Agent</h3><p>Works with approved sources, defined outputs, measurable standards and a named human owner.</p></article>)}</div></section>
  <section className="industry-outcomes section-cobalt"><div className="section-head page-grid"><p className="section-index">04 / Business outcomes</p><div><p className="kicker">What changes operationally</p><h2>Less fragmented work. More visible operating leverage.</h2></div></div><div className="outcome-grid page-grid">{industry.outcomes.map((outcome,index)=><div key={outcome}><span>0{index+1}</span><strong>{outcome}</strong></div>)}</div></section>
  <section className="related-services section-light"><div className="section-head page-grid"><p className="section-index">05 / Connected capability</p><div><p className="kicker">Build the operating layer</p><h2>Platform, services and industry intelligence—together.</h2></div></div><div className="related-grid page-grid"><Link href="/en/platform/agents"><p className="kicker">Platform</p><h3>AI Agent Platform</h3><p>Deploy governed roles connected to data, workflows and approval.</p><span>Explore ↗</span></Link><Link href="/en/services/ai-transformation"><p className="kicker">Strategy</p><h3>AI Transformation</h3><p>Prioritise opportunities and build a practical 90-day roadmap.</p><span>Explore ↗</span></Link><Link href="/en/services/seo-aeo"><p className="kicker">Visibility</p><h3>SEO & AEO</h3><p>Become easier to discover in search and AI-generated answers.</p><span>Explore ↗</span></Link></div></section>
  <PageFinalCta title={`Benchmark your ${industry.name.toLowerCase()} operations against the market.`} copy="In five minutes, see where demand, visibility, workflow and customer signals reveal the first high-value AI opportunity." />
  </main></SiteShell>}
