export type PlatformCapability = {
  slug: string; code: string; eyebrow: string; title: string; accent: string;
  intro: string; promise: string; proof: string;
  metrics: { value: string; label: string }[];
  workflow: { title: string; copy: string }[];
  outcomes: string[];
};

export const platformCapabilities: PlatformCapability[] = [
  { slug:"intelligence",code:"P/04",eyebrow:"Always-on market intelligence",title:"See the shift before it becomes the story.",accent:"Signal",intro:"Turn fragmented market, competitor, search, social, and customer signals into a live decision layer for teams across Asia.",promise:"From noise to the next best question",proof:"Agents monitor continuously, explain what changed, and route only material signals to the people who can act.",metrics:[{value:"24/7",label:"signal monitoring"},{value:"8",label:"Asian markets"},{value:"1",label:"decision layer"},{value:"Human",label:"validated priorities"}],workflow:[{title:"Observe",copy:"Track approved market, brand, competitor, search, and conversation sources."},{title:"Classify",copy:"Connect signals to entities, themes, audiences, markets, and business priorities."},{title:"Interpret",copy:"Explain material movement, confidence, context, and likely implications."},{title:"Activate",copy:"Route alerts, briefs, and recommended actions into team workflows."}],outcomes:["Earlier category and competitor awareness","Decision-ready regional intelligence briefs","A shared evidence layer across markets","Less time spent assembling monitoring reports"]},
  { slug:"data-analysis",code:"P/05",eyebrow:"Connected business analysis",title:"Every metric should lead somewhere.",accent:"Decide",intro:"Connect media, CRM, commerce, analytics, and operational data so teams receive explanations, anomalies, and next actions—not another reporting queue.",promise:"A living brief, not a static dashboard",proof:"Analysis agents reconcile definitions, investigate changes, and present decisions with traceable source context.",metrics:[{value:"200+",label:"connection patterns"},{value:"Always",label:"on analysis"},{value:"One",label:"KPI language"},{value:"Traceable",label:"source context"}],workflow:[{title:"Connect",copy:"Bring approved performance and commercial sources into a governed analysis layer."},{title:"Reconcile",copy:"Standardise business definitions, time windows, attribution, and market context."},{title:"Explain",copy:"Detect anomalies and identify the drivers that matter to the operating objective."},{title:"Recommend",copy:"Deliver prioritised actions, owners, and measurable follow-up questions."}],outcomes:["Faster weekly and monthly reporting","Consistent KPI definitions across teams","Automated anomaly detection and explanation","More analyst time for judgment and strategy"]},
  { slug:"creative-studio",code:"P/06",eyebrow:"AI creative operations",title:"Scale expression. Keep the brand human.",accent:"Create",intro:"Transform insight and brand rules into multilingual briefs, concepts, copy, and variants—with human taste and approval built into every publishable step.",promise:"Creative velocity with a point of view",proof:"The system generates options from approved context; people direct the idea, choose the standard, and own what goes live.",metrics:[{value:"3×",label:"operating output"},{value:"Multi",label:"language workflows"},{value:"100%",label:"approval ready"},{value:"Brand",label:"rules embedded"}],workflow:[{title:"Ground",copy:"Combine the campaign objective, audience insight, brand system, and channel reality."},{title:"Imagine",copy:"Explore creative territories and messaging angles instead of producing random volume."},{title:"Produce",copy:"Create coordinated, multilingual copy and asset directions for each channel."},{title:"Learn",copy:"Feed review decisions and performance signals into the next creative cycle."}],outcomes:["More strategically distinct creative options","Faster multilingual production cycles","Consistent brand and compliance review","Performance learning connected to creation"]},
  { slug:"marketing-strategy",code:"P/07",eyebrow:"Agent-powered growth planning",title:"Turn strategy into an operating rhythm.",accent:"Orchestrate",intro:"Coordinate audiences, channels, content, timing, budgets, and lifecycle actions around one measurable business priority.",promise:"The plan stays alive after the workshop",proof:"Strategy agents keep assumptions visible, watch the evidence, and translate shifts into controlled operating recommendations.",metrics:[{value:"One",label:"growth objective"},{value:"Full",label:"journey view"},{value:"Weekly",label:"learning cycles"},{value:"Shared",label:"team priorities"}],workflow:[{title:"Frame",copy:"Define the commercial objective, constraints, audience, market, and success measures."},{title:"Model",copy:"Connect demand signals, journey friction, channel roles, and resource trade-offs."},{title:"Plan",copy:"Create an integrated action system with owners, timing, approval, and measures."},{title:"Adapt",copy:"Review performance continuously and propose evidence-based changes."}],outcomes:["One connected view of the customer journey","Faster response to market movement","Clearer channel and team responsibilities","Strategy linked directly to measurement"]},
  { slug:"workflow-automation",code:"P/08",eyebrow:"Multi-step agent workflows",title:"Remove the queue. Preserve the judgment.",accent:"Operate",intro:"Redesign recurring work as observable agent workflows with approved inputs, clear ownership, escalation rules, and human decisions where they matter.",promise:"Automation that knows when to stop",proof:"Every flow separates repeatable execution from exceptions, material decisions, and moments requiring human care.",metrics:[{value:"24/7",label:"workflow execution"},{value:"Clear",label:"exception queues"},{value:"Full",label:"audit history"},{value:"Human",label:"decision rights"}],workflow:[{title:"Map",copy:"Document triggers, inputs, handoffs, decisions, exceptions, and service standards."},{title:"Design",copy:"Assign agent roles and human ownership around a measurable output contract."},{title:"Connect",copy:"Integrate approved systems and introduce observable state at every handoff."},{title:"Improve",copy:"Measure quality, time, exceptions, and business impact to refine the flow."}],outcomes:["Shorter cycle time for recurring work","More consistent execution standards","Visible exception and approval queues","A measurable path from pilot to scale"]},
  { slug:"integrations",code:"P/09",eyebrow:"Enterprise integration layer",title:"Agents belong inside the business—not beside it.",accent:"Connect",intro:"Route governed context between CRM, messaging, analytics, advertising, commerce, content, and internal tools so agents can work across the real journey.",promise:"Your stack becomes agent-ready",proof:"FIMMICK designs the context, permissions, events, actions, and monitoring each workflow needs—without creating another disconnected data island.",metrics:[{value:"200+",label:"tool connections"},{value:"API",label:"and event ready"},{value:"Role",label:"based access"},{value:"Live",label:"workflow context"}],workflow:[{title:"Discover",copy:"Map systems, data owners, events, permissions, quality, and operational dependencies."},{title:"Model",copy:"Define the smallest trusted context each agent role requires to perform safely."},{title:"Route",copy:"Connect triggers, reads, writes, approvals, and observability across the workflow."},{title:"Control",copy:"Monitor access, errors, quality, latency, and changes as the system scales."}],outcomes:["Less manual movement between systems","Reliable context for agent decisions","Reusable integration services across workflows","Clear ownership of data and actions"]},
  { slug:"governance",code:"P/10",eyebrow:"Human-led AI governance",title:"Give autonomy a boundary—and a reason.",accent:"Govern",intro:"Make data access, permitted actions, approval thresholds, evidence, accountability, and improvement visible across every agent role.",promise:"Control designed into the workflow",proof:"Governance becomes a daily operating system: proportionate to risk, legible to teams, and measurable over time.",metrics:[{value:"Every",label:"role has an owner"},{value:"Every",label:"action has a boundary"},{value:"Every",label:"output has evidence"},{value:"Every",label:"change is reviewed"}],workflow:[{title:"Define",copy:"Set purpose, owners, data boundaries, prohibited actions, and outcome measures."},{title:"Approve",copy:"Place human judgment at publication, material spend, sensitive data, and exceptions."},{title:"Evidence",copy:"Maintain sources, review history, actions, versions, outcomes, and corrections."},{title:"Evolve",copy:"Review performance and incidents to update rules, roles, and controls."}],outcomes:["Clear decision rights for people and agents","Visible evidence and audit trails","Risk-based approval rather than blanket friction","Greater confidence to scale proven workflows"]},
];

export const getPlatformCapability = (slug: string) => platformCapabilities.find((item) => item.slug === slug);
