import type { Metadata } from "next";
import Link from "next/link";
import { SiteShell } from "@/app/components/site-shell";
import { Breadcrumbs, SubpageHero } from "@/app/components/subpage";
import { articles, caseStudies, migrationRows, services } from "@/app/data";

export const metadata:Metadata={title:"FIMMICK Website Launch Plan",description:"Internal implementation dossier for the FIMMICK website redesign.",robots:{index:false,follow:false}};

const templates=[
  ["Home","Cinematic operating narrative: problem → capability → agents → deployment → services → integrations → Asia → proof → insights → conversion."],
  ["Platform","Agent roles, workflow architecture, data model, governance, enterprise capability, and current plan positioning."],
  ["AI Transformation","Maturity assessment, prioritisation, agent design, integration, enablement, governance, and executive outcomes."],
  ["Services Hub","Objective-led paths: Acquire, Convert, Retain, Understand, Automate, Scale."],
  ["Service Detail","Inputs, workflow, outputs, impact, capability list, approval flow, related services, and conversion CTA."],
  ["Case Study Index","Editorial proof library, qualitative filters, substantiated metrics, and case pathways."],
  ["Case Study Detail","Overview, challenge, strategy, workflow, delivered work, outcomes, related services, and CTA."],
  ["Knowledge Hub","Featured intelligence, category filters, article cards, and topic hubs."],
  ["Article","Metadata, breadcrumbs, table of contents, author block, related content, internal links, and Article schema."],
  ["About","2008 origin, journey, method, ecosystem, Asia footprint, culture, and proof."],
  ["Contact","Benchmark, workshop, demo, and transformation intent routing with direct verified contact details."],
];

const shotList=[
  ["01","The AI Workforce Awakens","16-second seamless loop. Fragmented multilingual signals and particles coordinate into agent nodes, routed data paths, and a restrained human-approval pulse. Dark negative space on centre-left."],
  ["02","Market Intelligence","Regional signal field, changing language tags, competitor movement, search and conversation waves resolving into a concise priority map."],
  ["03","Content & Creative","Words, layouts, channel formats, and campaign fragments assemble into controlled variants, then pause at an editorial approval gate."],
  ["04","CRM & Customer Engagement","Anonymous relationship nodes move through lifecycle states as approved messages and human escalations route through the system."],
  ["05","Reporting & Optimisation","Fragmented performance streams reconcile into a few clear executive signals, recommended actions, and measured feedback loops."],
];

export default function LaunchPlanPage(){return <SiteShell><main id="main-content" className="launch-plan">
  <div className="subpage-nav page-grid"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Launch Plan"}]} /></div>
  <SubpageHero eyebrow="Internal implementation dossier / v1" title={<>FIMMICK website<br/><em>launch system.</em></>} intro="The sitemap, content architecture, template system, motion direction, production assets, responsive behaviour, migration logic, and launch checklist behind the rebuilt experience." code="D/01" />
  <nav className="dossier-nav page-grid" aria-label="Launch plan sections">{["Sitemap","Templates","Design system","Motion","Video","Responsive","SEO","Performance","Accessibility","Analytics","Build plan"].map((item,index)=><a href={`#dossier-${index+1}`} key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</a>)}<Link href="/launch-plan/github-report"><span>12</span>GitHub report</Link></nav>

  <section className="dossier-section section-light" id="dossier-1"><div className="dossier-heading page-grid"><p className="section-index">01 / Sitemap & migration</p><div><h2>Preserve authority. Clarify the system.</h2><p>English paths retain the existing <code>/en/</code> architecture. High-value service, article, case, company, conversion, ecosystem, and legal paths remain discoverable.</p></div></div><div className="dossier-table page-grid" role="table"><div className="dossier-row dossier-head"><span>Current URL</span><span>Target URL</span><span>Migration action</span></div>{migrationRows.map((row)=><div className="dossier-row" key={row[0]}>{row.map((cell)=><span key={cell}>{cell}</span>)}</div>)}</div><div className="sitemap-columns page-grid"><div><h3>Primary</h3>{["/","/en/platform/agents","/en/ai-transformation","/en/services","/en/case-studies","/en/knowledge-hub","/en/about","/en/contact"].map(x=><code key={x}>{x}</code>)}</div><div><h3>Service detail ({services.length})</h3>{services.map(s=><code key={s.slug}>/en/services/{s.slug}</code>)}</div><div><h3>Content & proof</h3>{caseStudies.map(s=><code key={s.slug}>/en/case-studies/{s.slug}</code>)}{articles.map(a=><code key={a.slug}>/en/knowledge-hub/{a.slug}</code>)}</div><div><h3>Continuity</h3>{["/en/workforce/growth","/en/workforce/operations","/en/workforce/finance","/en/workforce/hr","/en/workforce/cx","/en/platform/marketplace","/en/platform/pricing","/en/events","/en/ai-workshop","/en/fimmick-ecosystem","/en/privacy","/en/terms","/en/cookies"].map(x=><code key={x}>{x}</code>)}</div></div></section>

  <section className="dossier-section section-offwhite" id="dossier-2"><div className="dossier-heading page-grid"><p className="section-index">02 / Page templates</p><div><h2>One system. Distinct page jobs.</h2></div></div><div className="template-table page-grid">{templates.map(([name,copy],index)=><article key={name}><span>{String(index+1).padStart(2,"0")}</span><h3>{name}</h3><p>{copy}</p></article>)}</div></section>

  <section className="dossier-section design-spec section-ink" id="dossier-3"><div className="dossier-heading page-grid"><p className="section-index">03 / Visual design system</p><div><h2>Operational, editorial, precise.</h2><p>A dark enterprise foundation with disciplined blue intelligence, crisp white typography, and lime reserved for approval, readiness, and primary action.</p></div></div><div className="design-system-grid page-grid"><div className="palette"><p className="kicker">Colour tokens</p>{[["Obsidian","#020509"],["Graphite","#101820"],["Midnight","#061329"],["Cobalt","#1855E8"],["Spectral cyan","#68DCFF"],["Approval lime","#C8FF62"],["System white","#F7F9FB"],["Editorial paper","#F1F1EB"]].map(([name,value])=><div key={value} style={{"--swatch":value} as React.CSSProperties}><i/><span>{name}</span><code>{value}</code></div>)}</div><div className="type-spec"><p className="kicker">Typography</p><h3>Display / Helvetica Neue</h3><p className="type-serif">Editorial accent / Baskerville</p><code>Technical UI / SFMono-Regular</code><dl><div><dt>Hero</dt><dd>clamp(80px, 11.3vw, 181px) / 0.76</dd></div><div><dt>Section</dt><dd>clamp(51px, 6.8vw, 125px) / 0.94</dd></div><div><dt>Body lead</dt><dd>17–24px / 1.45–1.6</dd></div><div><dt>UI</dt><dd>8–11px / mono / uppercase</dd></div></dl></div><div className="spacing-spec"><p className="kicker">Grid & spacing</p><strong>12</strong><span>responsive columns</span><dl><div><dt>Maximum width</dt><dd>1440px</dd></div><div><dt>Desktop gutter</dt><dd>24px</dd></div><div><dt>Mobile gutter</dt><dd>18px</dd></div><div><dt>Section rhythm</dt><dd>98–150px</dd></div><div><dt>Radius</dt><dd>0px / sharp operational cards</dd></div><div><dt>Divider</dt><dd>1px / 12–20% opacity</dd></div></dl></div></div><div className="component-spec page-grid">{["Persistent navigation + benchmark CTA","Metric band","Editorial capability card","Agent constellation + detail inspector","Workflow sequence","Expandable service system","Regional signal map","Case-study editorial card","Article and topic grid","Benchmark conversion block"].map((item,index)=><span key={item}><i>0{index+1}</i>{item}</span>)}</div></section>

  <section className="dossier-section section-light" id="dossier-4"><div className="dossier-heading page-grid"><p className="section-index">04 / Motion system</p><div><h2>Motion explains state and responsibility.</h2><p>Animation is tied to observing, coordinating, approving, routing, and learning. No scroll-jacking; all motion degrades cleanly.</p></div></div><div className="motion-table page-grid">{[["Hero loop","16s seamless; fragmented → coordinated → fragmented; video pauses off-screen."],["Text reveal","420–680ms, 40–80ms stagger, translateY + opacity; one entry only."],["Counters","1.1s cubic-out; triggers once at 55% viewport; static for reduced motion."],["Agent paths","2.4–8s restrained pulses; active role increases local contrast."],["Scroll masks","8–12% vertical travel; no pinned interaction longer than one viewport."],["Cards","2–7px depth; 250–350ms; keyboard focus matches hover state."],["Data dividers","Low-amplitude linear scans; never compete with reading."],["Reduced motion","Poster replaces video; transforms and loops disabled; content remains complete."]].map(([name,copy],index)=><article key={name}><span>0{index+1}</span><h3>{name}</h3><p>{copy}</p></article>)}</div></section>

  <section className="dossier-section section-midnight" id="dossier-5"><div className="dossier-heading page-grid"><p className="section-index">05 / Video production</p><div><h2>Five visual stories. One operating language.</h2><p>Silent, abstract, dark, adaptive, and free of people, humanoid robots, fake dashboards, literal brains, and exposed customer data.</p></div></div><div className="shot-list page-grid">{shotList.map(([number,title,copy])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p><code>Palette: obsidian / cobalt / cyan / white / restrained lime. Camera: slow forward dolly. Lighting: volumetric, soft haze, refined grain. Output: AV1 WebM + H.264 MP4 + poster.</code></div></article>)}</div><div className="video-prompt page-grid"><p className="kicker">Master generation prompt</p><p>“A calm, premium abstract enterprise AI operations environment. Layered volumetric data fields, luminous particles, multilingual market signals, anonymous relationship nodes, campaign fragments, performance paths, and approval pulses organise from noise into a coordinated agent network. Slow forward camera movement, deep obsidian space, electric cobalt and cool cyan intelligence, restrained acid-lime approval accents, refined film grain, dark negative space for typography, seamless loop. No people, faces, hands, robots, brains, neon city, logos, or fake interface.”</p></div></section>

  <section className="dossier-section section-light" id="dossier-6"><div className="dossier-heading page-grid"><p className="section-index">06 / Responsive implementation</p><div><h2>Mobile is a different composition, not a small desktop.</h2></div></div><div className="responsive-grid page-grid">{[["≤ 760px","Single-column story; video reframed to 64% position; 2×2 proof band; tap-first service and agent controls; 18px page gutter."],["761–1180px","Two-column capability and insight cards; stacked agent inspector; 2×2 workflow steps; compact header navigation."],["1181–1600px","12-column editorial grid; four-up systems; full agent constellation; 24px gutters; max-width 1440px."],["> 1600px","Content width remains controlled; video and atmospheric fields can bleed; body measure does not expand."]].map(([range,copy])=><article key={range}><strong>{range}</strong><p>{copy}</p></article>)}</div></section>

  <section className="dossier-section checklist-section section-offwhite" id="dossier-7"><div className="dossier-heading page-grid"><p className="section-index">07 / SEO & schema</p><div><h2>Protect URLs. Improve entity clarity.</h2></div></div><div className="checklist-grid page-grid">{["Preserve /en/ service, case, article, contact, company, ecosystem, and legal routes.","Use explicit canonicals and hreflang for English, Traditional Chinese, Simplified Chinese, and future Japanese.","Retain article slugs, dates, categories, authors, related content, and internal links.","Implement Organization, Service, SoftwareApplication, Article, BreadcrumbList, and appropriate FAQ schema.","Separate platform, transformation, service, and insight intent to avoid keyword cannibalisation.","Use direct factual answers and substantiated proof for AI-search visibility.","Create 301 rules only for genuinely changed paths; validate chains and eliminate redirect loops.","Submit XML sitemap and test robots, canonicals, indexability, and structured data before cutover."].map((item,index)=><p key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</p>)}</div></section>

  <section className="dossier-section checklist-section section-light" id="dossier-8"><div className="dossier-heading page-grid"><p className="section-index">08 / Performance</p><div><h2>Cinematic without the penalty.</h2></div></div><div className="checklist-grid page-grid">{["Hero video: 16s, 960×540, 24fps; current build ~157KB AV1 WebM + ~674KB H.264 MP4.","Poster is 21KB and becomes the reduced-motion and no-video fallback.","Preload metadata only; video muted, looped, playsInline, paused off-screen.","Lazy-load non-critical media; reserve dimensions; avoid layout shift.","Use one procedural cinematic system instead of page-wide WebGL.","Keep interface animation CSS-first; add heavier libraries only where a measured interaction needs them.","Prioritise the headline, primary CTA, and poster for LCP; defer lower-story visual systems.","Set performance budgets for LCP, INP, CLS, JS, image, and video weight in CI."].map((item,index)=><p key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</p>)}</div></section>

  <section className="dossier-section checklist-section section-offwhite" id="dossier-9"><div className="dossier-heading page-grid"><p className="section-index">09 / Accessibility</p><div><h2>Enterprise quality includes access.</h2></div></div><div className="checklist-grid page-grid">{["WCAG 2.2 AA colour contrast and visible keyboard focus.","Semantic landmarks, one page-level H1, logical heading order, and skip navigation.","Keyboard- and touch-operable navigation, agent inspector, accordions, filters, and conversion controls.","Decorative video and abstract data art hidden from assistive technology.","Reduced-motion mode removes loops and transforms while retaining all information.","Static poster and complete HTML content when video, JavaScript, or advanced graphics are unavailable.","Captions or transcripts for future non-decorative video content.","44px minimum interactive targets on mobile and no hover-only information."].map((item,index)=><p key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</p>)}</div></section>

  <section className="dossier-section checklist-section section-light" id="dossier-10"><div className="dossier-heading page-grid"><p className="section-index">10 / Analytics</p><div><h2>Measure the decision journey.</h2></div></div><div className="checklist-grid page-grid">{["Define benchmark_start, workshop_request, demo_request, contact_email, and contact_call as primary conversions.","Track platform_agent_select, service_expand, service_detail_view, case_view, article_depth, and related_content_click.","Pass page type, business objective, service, article category, market, locale, and CTA position as clean dimensions.","Connect qualified lead outcomes back to source and content pathway through CRM.","Respect consent and regional privacy requirements; avoid sensitive payloads and exposed personal data.","Create executive funnel: engaged visit → proof interaction → service/platform depth → conversion intent → qualified opportunity."].map((item,index)=><p key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</p>)}</div></section>

  <section className="dossier-section build-plan section-cobalt" id="dossier-11"><div className="dossier-heading page-grid"><p className="section-index">11 / Production build plan</p><div><h2>From approved direction to controlled cutover.</h2></div></div><div className="build-steps page-grid">{[["01","Inventory","Export current URLs, metadata, content, media, schema, internal links, analytics, forms, and backlinks."],["02","Content model","Map services, agents, cases, articles, authors, categories, locales, proof, contacts, and legal content into structured records."],["03","Component system","Build Next.js App Router templates, content primitives, motion tokens, schema helpers, and locale-aware navigation."],["04","Asset production","Produce final video masters, posters, social previews, image derivatives, compression, and delivery rules."],["05","Migration","Import approved copy and media; preserve URLs; prepare 301 table; validate metadata and internal links."],["06","Integration","Connect CMS, forms, CRM, benchmark flow, analytics, consent, search, and regional language infrastructure."],["07","QA","Run content, browser, accessibility, performance, structured-data, analytics, and cross-device acceptance checks."],["08","Cutover","Freeze content, crawl both environments, deploy redirects, switch DNS, submit sitemaps, and monitor errors and conversion."],["09","Optimise","Review search visibility, AI answers, lead quality, behaviour, Core Web Vitals, and agent-content performance monthly."]].map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
</main></SiteShell>}
