import type { Metadata } from "next";
import { ContactIntent } from "@/app/components/interactive";
import { SiteShell } from "@/app/components/site-shell";
import { Breadcrumbs, SubpageHero } from "@/app/components/subpage";

export const metadata:Metadata={title:"Contact FIMMICK — Benchmark, Workshop or Demo",description:"Request a free industry benchmark, AI workshop, platform demo, or transformation conversation with FIMMICK in Hong Kong.",alternates:{canonical:"https://www.fimmick.com/en/contact"}};
export default function ContactPage(){return <SiteShell><main id="main-content" className="contact-page">
  <div className="subpage-nav page-grid"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Contact"}]} /></div>
  <SubpageHero eyebrow="Contact / choose a starting point" title={<>Turn the first question<br/>into an <em>operating plan.</em></>} intro="Tell us what needs to change. We’ll match the objective with the right benchmark, workshop, platform conversation, and transformation team." code="X/01" />
  <section className="contact-section section-offwhite"><div className="contact-layout page-grid"><div className="contact-options"><div><p className="kicker">Free industry benchmark</p><h2>See where the business stands.</h2><p>Map category signals, competitor movement, operational gaps, and the first areas where an agent workflow may create value.</p><span>Best for / Leaders establishing a fact base</span></div><div><p className="kicker">AI workshop</p><h2>Align the leadership team.</h2><p>A practical discussion of workflow opportunities, operating responsibility, data readiness, governance, and the first 90 days.</p><span>Best for / Executive and functional teams</span></div><div><p className="kicker">Platform demo</p><h2>Inspect the agent operating model.</h2><p>Walk through roles, inputs, task execution, outputs, review gates, integrations, dashboards, and enterprise configuration.</p><span>Best for / Teams assessing deployment</span></div></div><ContactIntent /></div></section>
  <section className="contact-direct section-ink"><div className="page-grid"><p className="section-index">Direct contact</p><div><p className="kicker">Hong Kong HQ</p><a className="contact-big-link" href="mailto:info@fimmick.com">info@fimmick.com <span>↗</span></a><a className="contact-big-link" href="tel:+85236225388">+852 3622 5388 <span>↗</span></a></div><div className="contact-hours"><p>For benchmarks, workshops, demonstrations, transformation programmes, and partnership enquiries.</p><p>We work across Hong Kong, Taiwan, Japan, Singapore, Malaysia, Thailand, the Philippines, and China.</p></div></div></section>
</main></SiteShell>}
